サブマニュアル更新しました
okadakazu/OfficeWorkManual pull request #1
Opened 2021-01-29 22:00 UTC by okadakazu

サブマニュアルの各項目を記入しました。問題がないか確認をお願いします。

2021-01-29 22:15 UTC, 286okada requested changes
メール設定の部分のみ修正検討してください。他はOKです。

2021-01-29 22:15 UTC, 286okada commented on sub_manual.md
> +Gmailの設定画面を表示し、＜アカウントとインポート＞で他のメールアドレスを追加してください。
これだと説明不足に感じます。
Gmailサーバーやポートの設定についても触れたほうがいいのではないでしょうか。

2021-01-30 21:37 UTC, okadakazu commented on sub_manual.md
> +Gmailの設定画面を表示し、＜アカウントとインポート＞で他のメールアドレスを追加してください。
承知しました。本日中に修正します。

2021-01-30 21:44 UTC, okadakazu commented
メール設定を加筆してプッシュしました。再確認お願いします。

2021-01-30 21:47 UTC, 286okada approved these changes
確認しました。これなら問題ありません。

2021-01-30 21:49 UTC, merged